spring.application.name=eglise
spring.datasource.url=jdbc:postgresql://localhost:5432/eglise_kto
spring.datasource.username=postgres
spring.datasource.password=isaia

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true